import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import ArticleList from '@/components/ArticleList'

const inter = Inter({ subsets: ['latin'] })

export default function Home({article}) {
  console.log(article)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name='keywords' content='web development, programming' />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Home Page</h1>
        <ArticleList article={article} />
      </main>
    </>
  )
}

export async function getStaticProps() {
  const res = await fetch(`https://jsonplaceholder.typicode.com/posts?_limit=6`);
  const article = await res.json();
  return {
    props: {
      article
    }
  }
}